server:
  port: 8888
spring:
  application:
    name: chat-ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:7b
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456



logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
