server:
  port: 8888
spring:
  application:
    name: oneCoupon-AI

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:7b
        temperature: 0.8 # 模型温度，值越大，输出结果越随机
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: sk-71b61c28906841d3aa33fa4d5496e67b
      chat:
        options:
          model: qwen-max-0125 # 可选择的模型
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.227.130:8848
        enabled: true
      password: nacos
      username: nacos
    inetutils:
      preferred-networks: 192.168    # 强制使用 IPv4（避免 IPv6 检测问题）
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
feign:
  client:
    config:
      default:  # 全局默认配置
        connect-timeout: 5000  # 连接超时（毫秒）
        read-timeout: 10000    # 读取超时（毫秒）
        logger-level: basic    # 日志级别（basic / full / none）


logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
