server:
  port: 10010

spring:
  application:
    name: oneCoupon-merchant-admin
  datasource:
#    url: jdbc:mysql://192.168.227.130:3306/one_coupon_rebuild?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456

# 修改为 ShardingSphere 自定义驱动
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.227.130:8848
        enabled: true
      password: nacos
      username: nacos

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.kongji.onecoupon

knife4j:
  enable: true
  setting:
    language: zh_cn
xxl-job:
  enabled: true
  access-token: default_token
  admin:
    addresses: http://localhost:8088/xxl-job-admin
  executor:
    application-name: one-coupon-merchant-admin
    ip: 127.0.0.1
    log-retention-days: 30
    port: 9999
rocketmq:
  name-server: 127.0.0.1:9876 # NameServer 地址，如果 VM 参数里设置了星球云服务器 RocketMQ 地址，运行时会替换
  producer:
    # 通用生产者组，其中的 ${unique-name:} 是为了避免大家公用一个 Topic，造成你发的消息被其他同学消费，其他同学发的消息被你消费等问题
    group: oneCoupon_merchant-admin${unique-name:}-service_common-message-execute_pg
    send-message-timeout: 2000 # 发送超时时间
    retry-times-when-send-failed: 1 # 同步发送重试次数
    retry-times-when-send-async-failed: 1 # 异步发送重试次数