

server:
  port: 10020

spring:
  application:
    name: oneCoupon-engine${unique-name:}
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.227.130:8848
        enabled: true
      password: nacos
      username: nacos
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.kongji.onecoupon

knife4j:
  enable: true
  setting:
    language: zh_cn

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: oneCoupon_engine${unique-name:}-service_common-message-execute_pg
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1

one-coupon:
  user-coupon-list:
    save-cache:
      type: direct # 有两个选项：direct 在流程里直接操作，binlog 通过解析数据库日志后操作
